In [1]:
import numpy as np
import h5py
import pickle
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
# goal is to get batches of from a training and test set with equal distribution of classes
# the shape of batch[0] and batch[1] should be like:  (examples, 450 * 460 * 3), (examples, 4)

In [ ]:
with h5py.File('oh_np.h5', 'a') as on:
    
    train_labels = on.get('onehot0')
    train_data = on.get('numpy0')
    print('initialized')
    
    for i in range(1,80):
        
        train_labels = np.append(train_labels, np.array(on.get('onehot'+str(i))), axis =0 )
        train_data = np.append(train_data, np.array(on.get('numpy'+str(i))), axis =0 )
        print('did',i)
        
with h5py.File('trainset.h5', 'a') as on:
    on.create_dataset('train_labels',data=train_labels,compression="gzip",compression_opts=9)
    on.create_dataset('train_data',data=train_data,compression="gzip",compression_opts=9) 
  

initialized


In [20]:
b = np.random.choice(a,82,replace=False)

In [21]:
b

array([ 2, 43, 40, 62, 19, 77, 20, 15, 63, 26, 74, 46, 65, 75, 31, 24, 49,
        7, 60, 17, 82, 25, 80, 52,  9,  3, 45, 36, 12, 67, 59, 70, 33,  6,
       42, 23, 55,  0, 47, 76,  5, 68, 64, 28, 56, 58, 48, 21, 78, 32,  8,
       18, 14, 13, 10, 51, 37, 22,  1, 34, 41, 81, 30, 61, 44,  4, 79, 16,
       72, 66, 71, 38, 27, 29, 53, 11, 54, 50, 35, 39, 57, 73])

In [22]:
from collections import Counter
c= [item for item, count in Counter(b).items() if count > 1]

In [49]:
a/2

array([[  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ],
       [  3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5],
       [  7. ,   7.5,   8. ,   8.5,   9. ,   9.5,  10. ],
       [ 10.5,  11. ,  11.5,  12. ,  12.5,  13. ,  13.5],
       [ 14. ,  14.5,  15. ,  15.5,  16. ,  16.5,  17. ],
       [ 17.5,  18. ,  18.5,  19. ,  19.5,  20. ,  20.5],
       [ 21. ,  21.5,  22. ,  22.5,  23. ,  23.5,  24. ],
       [ 24.5,  25. ,  25.5,  26. ,  26.5,  27. ,  27.5]])

In [42]:
with h5py.File('oh_np.h5', 'a') as on:
    #print(list(on.keys()))
    onehot = np.array(on.get('onehot80'))
    summed = np.sum(onehot,axis=0)
print(summed)

[  86.  334.   72.    8.]


In [45]:
with h5py.File('oh_np.h5', 'a') as on:
    #on.create_dataset("severe", data = zeros, compression="gzip", compression_opts=9)
    for i in range(80):
        print('Array',i)
        onehot = np.array(on.get('onehot'+str(i)))
        rows,_ = onehot.shape
        zeros = np.zeros((450,460,3))
        zeros = np.expand_dims(zeros,axis=0)
        for j in range(rows):
            if np.argmax(onehot[j]) == 2:
                print("found one",j)
                addarr = np.expand_dims(np.array(on.get('numpy'+str(i))[j]),axis=0)
                zeros = np.append(zeros,addarr,axis=0)
        zeros = np.delete(zeros,0,0)
        print('save', "mild"+str(i), zeros.shape)
        on.create_dataset("mild"+str(i), data = zeros, compression="gzip", compression_opts=9)
print('DONE')

Array 0
found one 4
found one 5
found one 10
found one 11
found one 24
found one 25
found one 40
found one 41
found one 56
found one 57
found one 64
found one 65
found one 66
found one 67
found one 72
found one 73
found one 90
found one 91
found one 94
found one 95
found one 96
found one 97
found one 100
found one 101
found one 102
found one 103
found one 104
found one 105
found one 124
found one 125
found one 132
found one 133
found one 134
found one 135
found one 156
found one 157
found one 158
found one 159
found one 162
found one 163
found one 164
found one 165
found one 184
found one 185
found one 186
found one 187
found one 210
found one 211
found one 216
found one 217
found one 218
found one 219
found one 222
found one 223
found one 226
found one 227
found one 244
found one 245
found one 258
found one 259
found one 268
found one 269
found one 302
found one 303
found one 346
found one 347
found one 362
found one 363
found one 408
found one 409
found one 412
found one 413
found on